tab_spaces = 4

# This is also the setting used by [rustc](https://github.com/rust-lang/rust/blob/master/rustfmt.toml)
use_small_heuristics = "Max"

# Use field initialize shorthand if possible
use_field_init_shorthand = true
