# https://github.com/stackblitz-labs/pkg.pr.new
name: Preview Commit

on: push

jobs:
  build:
    name: Build bindings and node packages
    uses: ./.github/workflows/reusable-release-build.yml

  publish:
    name: Pkg Preview
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Git Reset Hard
        run: git reset --hard # fix pnpm install add new line for package.json

      - name: Download Binding Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/workspace-tools/artifacts

      - name: Move Binding Artifacts
        run: pnpm --filter workspace-tools artifacts

      - name: List Bindings
        run: ls -R ./packages/workspace-tools/npm
        shell: bash

      - name: List Artifacts
        run: ls -R ./packages/workspace-tools/artifacts
        shell: bash

      - name: Download Node Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages/workspace-tools/dist
          name: node-artifact

      - name: List Node Artifacts
        run: ls -R ./packages/workspace-tools/dist
        shell: bash
